<a href="https://colab.research.google.com/github/xqmmy/tensorflow2.0/blob/master/%E5%BC%A0%E9%87%8F%E4%B8%8E%E5%B8%B8%E8%A7%81%E6%93%8D%E4%BD%9C.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import tensorflow as tf

In [0]:
# 张量的操作

In [5]:
# Rank 0
mammal=tf.Variable("cat",tf.string)
tf.print(tf.rank(mammal))
tf.print(tf.shape(mammal))

0
[]


In [6]:
print(tf.rank(mammal))

tf.Tensor(0, shape=(), dtype=int32)


In [7]:
#Rank 1
mystr=tf.Variable(["Hello"],tf.string)
tf.print(tf.rank(mystr))
tf.print(tf.shape(mystr))

1
[1]


In [8]:
#Rank 2
mymat=tf.Variable([[7],[11]],tf.int16)
tf.print(tf.rank(mymat))
tf.print(tf.shape(mymat))

2
[2 1]


In [9]:
#创建张量
tf.constant([1,2,3],dtype=tf.int16)

<tf.Tensor: shape=(3,), dtype=int16, numpy=array([1, 2, 3], dtype=int16)>

In [10]:
tf.zeros((2,2),dtype=tf.int16)

<tf.Tensor: shape=(2, 2), dtype=int16, numpy=
array([[0, 0],
       [0, 0]], dtype=int16)>

In [14]:
rank_three_tensor=tf.ones([3,4,5])
rank_three_tensor

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]], dtype=float32)>

In [15]:
matrix=tf.reshape(rank_three_tensor,[6,10])
matrix

<tf.Tensor: shape=(6, 10), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [16]:
#字符切割
tf.strings.bytes_split('process')

<tf.Tensor: shape=(7,), dtype=string, numpy=array([b'p', b'r', b'o', b'c', b'e', b's', b's'], dtype=object)>

In [17]:
#单词切割
tf.strings.split('how are you')

<tf.Tensor: shape=(3,), dtype=string, numpy=array([b'how', b'are', b'you'], dtype=object)>

In [0]:
#tf自带debug函数
a=tf.random.uniform((10,10))
tf.debugging.assert_equal(x=a.shape,y=(10,10))

In [19]:
a = tf.random.uniform(shape=(10,5),minval=0,maxval=10)
a

<tf.Tensor: shape=(10, 5), dtype=float32, numpy=
array([[5.6971025 , 1.485548  , 1.0857177 , 0.11381745, 0.33410788],
       [9.342882  , 5.0783386 , 0.25604248, 9.524856  , 9.407173  ],
       [2.2291708 , 7.786083  , 7.6321483 , 8.70846   , 2.8494883 ],
       [8.069924  , 4.5163336 , 5.560936  , 1.546551  , 4.871514  ],
       [8.414236  , 3.3890462 , 0.24195552, 7.9874396 , 6.8086185 ],
       [6.8200455 , 9.729386  , 9.838596  , 9.303618  , 2.9440987 ],
       [1.0381007 , 0.93303084, 0.8447206 , 8.647412  , 6.251805  ],
       [9.879711  , 9.617047  , 5.918742  , 0.11989474, 6.891477  ],
       [5.303668  , 4.047905  , 8.083669  , 3.0990446 , 5.4635153 ],
       [8.315069  , 4.076252  , 5.164969  , 4.907175  , 4.9256363 ]],
      dtype=float32)>

In [20]:
a = tf.constant([[1,2],[3,4]])
b = tf.constant([[5,6],[7,8]])

tf.print(tf.math.add(a,b))
tf.print(tf.math.subtract(a,b))
tf.print(tf.math.multiply(a,b))
tf.print(tf.math.divide(a,b))

[[6 8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[5 12]
 [21 32]]
[[0.2 0.33333333333333331]
 [0.42857142857142855 0.5]]


In [21]:
print(tf.math.add(a,b))

tf.Tensor(
[[ 6  8]
 [10 12]], shape=(2, 2), dtype=int32)


In [22]:
x =tf.constant([1.8,2.2],dtype=tf.float32)

x1=tf.dtypes.cast(x,tf.int32)
x1

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2], dtype=int32)>

In [0]:
#文本分类

a = tf.random.uniform(shape = (10,100,50),minval=-0.5,maxval=0.5) #张量

x = tf.keras.layers.LSTM(100)(a) #LSTM

x = tf.keras.layers.Dense(10)(x) #全连接层

x = tf.nn.softmax(x) #激活函数

In [0]:
#层中增加激活函数
tf.keras.layers.Dense(64, activation='relu')
#or
tf.keras.layers.Dense(64, activation=tf.nn.relu)


#将L1正则化系数为0.01的线性层应用于内核矩阵
tf.keras.layers.Dense(64, kernel_regularizer=tf.keras.regularizers.l1(0.01))

# 将L2正则化系数为0.01的线性层应用于偏差向量：
tf.keras.layers.Dense(64, bias_regularizer=tf.keras.regularizers.l2(0.01))

# 内核初始化为随机正交矩阵的线性层：
tf.keras.layers.Dense(64, kernel_initializer='orthogonal')

# 偏差向量初始化为2.0的线性层：
tf.keras.layers.Dense(64, bias_initializer=tf.keras.initializers.Constant(2.0))